### ISSUE TITLE
Multiple h1 tags

### ISSUE THREAD

**Issue by zachfedor** [JodyWinters/JodyWinters.github.io#1]
https://github.com/JodyWinters/JodyWinters.github.io/blob/7855adae6a8c8105fc93220c49fe1583bea6ce6c/index.html#L9-L10

The web world is split if multiple `<h1>` tags is okay or not. I'd take the safe option and avoid it. This is kind of saying you have two sections, one for your name with no content, and a second related section labeled "Homepage/About Me" with the rest of the content.

**Comment by JodyWinters** [comment]
Changed my name to a p tag to have only 1 h1 tag
